/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    flowers: Flower;
    'cultivation-logs': CultivationLog;
    categories: Category;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    flowers: FlowersSelect<false> | FlowersSelect<true>;
    'cultivation-logs': CultivationLogsSelect<false> | CultivationLogsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'page-content': PageContent;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'page-content': PageContentSelect<false> | PageContentSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrivez l'image pour les personnes malvoyantes et le SEO.
   */
  alt: string;
  /**
   * S'affiche sous l'image.
   */
  caption?: string | null;
  /**
   * Ex: © Photographe / Unsplash.
   */
  attribution?: string | null;
  licenseType?: ('public_domain' | 'cc_by' | 'purchased' | 'copyright' | 'unknown') | null;
  /**
   * Lien vers la source de l'image.
   */
  sourceUrl?: string | null;
  /**
   * Analyse de l'IA ou vos remarques.
   */
  licenseNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Généré automatiquement à partir du titre
   */
  slug?: string | null;
  publishedDate?: string | null;
  category?: (number | null) | Category;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Généré automatiquement à partir du titre
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flowers".
 */
export interface Flower {
  id: number;
  name: string;
  /**
   * Généré automatiquement à partir du nom
   */
  slug?: string | null;
  description?: string | null;
  price?: number | null;
  stock?: number | null;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  season?: ('spring' | 'summer' | 'autumn' | 'winter')[] | null;
  waterNeeds?: ('low' | 'medium' | 'high') | null;
  sunExposure?: ('shadow' | 'part_shade' | 'sun') | null;
  sowingPeriod?:
    | ('jan' | 'feb' | 'mar' | 'apr' | 'may' | 'jun' | 'jul' | 'aug' | 'sep' | 'oct' | 'nov' | 'dec')[]
    | null;
  harvestPeriod?:
    | ('jan' | 'feb' | 'mar' | 'apr' | 'may' | 'jun' | 'jul' | 'aug' | 'sep' | 'oct' | 'nov' | 'dec')[]
    | null;
  technicalNotes?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cultivation-logs".
 */
export interface CultivationLog {
  id: number;
  date: string;
  flower: number | Flower;
  action: 'sowing' | 'planting' | 'care' | 'observation' | 'harvest';
  notes?: string | null;
  photos?:
    | {
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Généré automatiquement à partir du nom
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categories?: (number | Category)[] | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Si ce produit (ex: un bouquet) contient des fleurs spécifiques de votre catalogue.
   */
  relatedFlowers?: (number | Flower)[] | null;
  price?: number | null;
  stock?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'flowers';
        value: number | Flower;
      } | null)
    | ({
        relationTo: 'cultivation-logs';
        value: number | CultivationLog;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  attribution?: T;
  licenseType?: T;
  sourceUrl?: T;
  licenseNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedDate?: T;
  category?: T;
  coverImage?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flowers_select".
 */
export interface FlowersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  stock?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  season?: T;
  waterNeeds?: T;
  sunExposure?: T;
  sowingPeriod?: T;
  harvestPeriod?: T;
  technicalNotes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cultivation-logs_select".
 */
export interface CultivationLogsSelect<T extends boolean = true> {
  date?: T;
  flower?: T;
  action?: T;
  notes?: T;
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  categories?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  relatedFlowers?: T;
  price?: T;
  stock?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: number;
  accueil?: {
    glanage?: ('open' | 'closed' | 'soon') | null;
    /**
     * Ex: "Les Dahlias sont là !"
     */
    meteoFleurs?: string | null;
    /**
     * S'affiche sur la page d'accueil.
     */
    whereIsCecile?: string | null;
    whereIsCecileEnabled?: boolean | null;
    /**
     * Par défaut : hero-accueil.png
     */
    heroImage?: (number | null) | Media;
    /**
     * Laissez vide pour utiliser la valeur par défaut.
     */
    heroSubText?: string | null;
    /**
     * Laissez vide pour utiliser la valeur par défaut.
     */
    philosophieTitle?: string | null;
    /**
     * Laissez vide pour utiliser la valeur par défaut.
     */
    philosophieText?: string | null;
    seoSectionEnabled?: boolean | null;
    /**
     * Ces trois blocs sont essentiels pour le référencement (mots-clés, localisation).
     */
    seoItems?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  laFerme?: {
    title?: string | null;
    subText?: string | null;
    histoireTitre?: string | null;
    /**
     * Si vide, affiche l'histoire par défaut (Cécile & Lison).
     */
    histoireTexte?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    histoireImage?: (number | null) | Media;
    ecologieTitre?: string | null;
    /**
     * Si vide, affiche les 3 points par défaut (Zéro Déchet, Biodiversité, Local).
     */
    ecologieItems?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  fleurs?: {
    title?: string | null;
    subText?: string | null;
    catalogueTitle?: string | null;
  };
  leMarche?: {
    title?: string | null;
    subText?: string | null;
    catalogueTitle?: string | null;
    /**
     * Texte expliquant qu'il n'y a pas de vente en ligne et qu'il faut contacter Cécile.
     */
    infoVenteEnLigne?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  blog?: {
    title?: string | null;
    subText?: string | null;
  };
  contact?: {
    title?: string | null;
    subText?: string | null;
    /**
     * Texte dédié aux fleuristes, magasins, etc.
     */
    prosSection?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Texte dédié aux particuliers.
     */
    particuliersSection?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Nom qui apparaîtra lors de l'enregistrement du contact.
     */
    nomOrganisation?: string | null;
    adresse?: string | null;
    codePostal?: string | null;
    ville?: string | null;
    telephone?: string | null;
    email?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    /**
     * Sans espaces ni caractères spéciaux pour le lien direct.
     */
    whatsapp?: string | null;
    horaires?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  aiDefaultProvider?: ('gemini' | 'claude' | 'openai') | null;
  geminiApiKey?: string | null;
  claudeApiKey?: string | null;
  openaiApiKey?: string | null;
  /**
   * Définissez ici comment l'IA doit s'exprimer par défaut.
   */
  aiSystemPrompt?: string | null;
  /**
   * Collez ici un ou deux articles que vous aimez particulièrement pour que l'IA s'en inspire (ton, vocabulaire, longueur).
   */
  aiExamples?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content_select".
 */
export interface PageContentSelect<T extends boolean = true> {
  accueil?:
    | T
    | {
        glanage?: T;
        meteoFleurs?: T;
        whereIsCecile?: T;
        whereIsCecileEnabled?: T;
        heroImage?: T;
        heroSubText?: T;
        philosophieTitle?: T;
        philosophieText?: T;
        seoSectionEnabled?: T;
        seoItems?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  laFerme?:
    | T
    | {
        title?: T;
        subText?: T;
        histoireTitre?: T;
        histoireTexte?: T;
        histoireImage?: T;
        ecologieTitre?: T;
        ecologieItems?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  fleurs?:
    | T
    | {
        title?: T;
        subText?: T;
        catalogueTitle?: T;
      };
  leMarche?:
    | T
    | {
        title?: T;
        subText?: T;
        catalogueTitle?: T;
        infoVenteEnLigne?: T;
      };
  blog?:
    | T
    | {
        title?: T;
        subText?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        subText?: T;
        prosSection?: T;
        particuliersSection?: T;
        nomOrganisation?: T;
        adresse?: T;
        codePostal?: T;
        ville?: T;
        telephone?: T;
        email?: T;
        instagram?: T;
        facebook?: T;
        whatsapp?: T;
        horaires?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  aiDefaultProvider?: T;
  geminiApiKey?: T;
  claudeApiKey?: T;
  openaiApiKey?: T;
  aiSystemPrompt?: T;
  aiExamples?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}